#version 460 core
layout(local_size_x = 256) in;

layout(std430, binding = 3) readonly buffer PEmit { vec4 pemit[]; };
layout(std430, binding = 8) buffer Radiance { vec4 rad[]; };

uniform uint u_num_leaves;
uniform uint u_tree_offset;
uniform float u_gain;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= u_num_leaves) return;
    rad[u_tree_offset + i] = vec4(pemit[i].rgb * u_gain, 1.0);
}
