add_subdirectory(01_hello_triangle)
add_subdirectory(02_clear_screen)
add_subdirectory(03_buffer_test)
add_subdirectory(04_pure_gl)
add_subdirectory(05_shader_file)
add_subdirectory(06_texture)
add_subdirectory(07_mesh_material)
add_subdirectory(08_renderer)
add_subdirectory(09_camera)
add_subdirectory(10_model)
add_subdirectory(11_sampler)
add_subdirectory(12_renderpass)
add_subdirectory(13_scene)
add_subdirectory(14_compute)
add_subdirectory(15_light)
add_subdirectory(16_bindless)
add_subdirectory(17_query)
add_subdirectory(18_indirect)
add_subdirectory(19_particles)
add_subdirectory(20_environment)
add_subdirectory(21_postproc)
add_subdirectory(22_gpu_driven)
add_subdirectory(23_imgui)
add_subdirectory(24_debug_draw)
add_subdirectory(25_pbr)
add_subdirectory(26_deferred)
add_subdirectory(27_mdc)
add_subdirectory(28_animation)
add_subdirectory(29_mdc_animation)
add_subdirectory(30_dragon_shading)
add_subdirectory(31_mesh_decomposition)
add_subdirectory(32_mdc_lighting)
